### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by gavinma86** [larrysu1115/flask-vue#1]
当运行python dodo/app.py时报错，ModuleNotFoundError: No module named '__main__.doggy'; '__main__' is not a package，python3环境 macos 10.15.5

**Comment by larrysu1115** [comment]
更新了运行指示 README.md, 请用下面指令运行:
```
# install required packages
$ pip install flask
$ pip install jsonify

# run example:
$ cd b2e
$ FLASK_DEBUG=1 FLASK_APP=dodo/app2.py flask run
```

可以参考这篇文章说明步骤：[http://blog.sws9f.org](http://blog.sws9f.org/programming/2018/05/15/flask-vue-skeleton.html)
